# Generated by Django 5.0.6 on 2024-05-16 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ordinary', 'Ordinary'), ('shopkeepers', 'Shopkeepers')], default='ordinary', max_length=11)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
